---
run:
  concurrency: 6
  deadline: 5m
linters:
  enable-all: true
  disable:
    - deadcode
    - dogsled
    - dupl
    - errcheck
    - exhaustivestruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godox
    - golint
    - gomnd
    - gosec
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - nosnakecase
    - prealloc
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
    - wsl
